return function(t)
  local apply = require("loopbiotic.apply")

  t.test("parse_hunk parses a normal hunk", function()
    local hunk = apply.parse_hunk("@@ -3,2 +3,2 @@\n context\n-old\n+new\n")
    t.eq(hunk.old_start, 3, "old_start")
    t.eq(hunk.old_len, 2, "old_len")
    t.eq(#hunk.lines, 3, "line count")
    t.eq(hunk.lines[3], { kind = "add", text = "new" })
    t.eq(hunk.old_lines, { "context", "old" })
  end)

  t.test("parse_hunk rejects multiple hunks", function()
    t.fails("exactly one hunk", function()
      apply.parse_hunk("@@ -1,1 +1,1 @@\n-a\n+b\n@@ -5,1 +5,1 @@\n-c\n+d\n")
    end)
  end)

  t.test("parse_hunk defaults old_len to 1 for @@ -N @@ headers", function()
    local hunk = apply.parse_hunk("@@ -7 @@\n-only\n+line\n")
    t.eq(hunk.old_start, 7, "old_start")
    t.eq(hunk.old_len, 1, "old_len")
  end)

  t.test("parse_hunk rejects a hunk without source context", function()
    t.fails("no source context", function()
      apply.parse_hunk("@@ -1,2 +1,3 @@\n+added only\n")
    end)
  end)

  t.test("parse_hunk rejects invalid patch lines", function()
    t.fails("Invalid patch line", function()
      apply.parse_hunk("@@ -1,1 +1,1 @@\n?what\n")
    end)
  end)

  t.test("apply_diff applies at an exactly matching header position", function()
    local out = apply.apply_diff({ "a", "b", "c" }, "@@ -2,1 +2,1 @@\n-b\n+B\n")
    t.eq(out, { "a", "B", "c" })
  end)

  t.test("apply_diff tolerates whitespace drift and keeps buffer lines", function()
    local out = apply.apply_diff({ "\tguard", "\told" }, "@@ -1,2 +1,2 @@\n guard  \n-    old\n+    new\n")
    t.eq(out, { "\tguard", "    new" })
  end)

  t.test("resolve_start relocates a hunk whose header start is stale", function()
    local out = apply.apply_diff({ "x", "target", "y" }, "@@ -9,1 +9,1 @@\n-target\n+replaced\n")
    t.eq(out, { "x", "replaced", "y" })
  end)

  t.test("resolve_start fails on ambiguous context", function()
    local hunk = apply.parse_hunk("@@ -9,1 +9,1 @@\n-same\n+other\n")
    t.fails("ambiguous", function()
      apply.resolve_start({ "same", "same" }, hunk)
    end)
  end)

  t.test("resolve_start fails on missing context", function()
    local hunk = apply.parse_hunk("@@ -1,1 +1,1 @@\n-absent\n+other\n")
    t.fails("not found", function()
      apply.resolve_start({ "something", "else" }, hunk)
    end)
  end)

  t.test("apply_diff creates content in an empty file", function()
    local out = apply.apply_diff({ "" }, "@@ -1,0 +1,2 @@\n+first\n+second\n")
    t.eq(out, { "first", "second" })
  end)

  t.test("resolve_start only creates files from empty sources", function()
    local hunk = apply.parse_hunk("@@ -1,0 +1,1 @@\n+first\n")
    t.eq(apply.resolve_start({}, hunk), 0, "empty source")
    t.eq(apply.resolve_start({ "" }, hunk), 0, "single blank line")
    t.fails("empty file", function()
      apply.resolve_start({ "occupied" }, hunk)
    end)
  end)
end
